language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO=Django==1.4.13
  - DJANGO=Django==1.5.8
  - DJANGO=Django==1.6.5
  - DJANGO=Django==1.7
install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
script:
  - python tests/manage.py test nap --settings=settings

matrix:
  exclude:
    - env: DJANGO=Django==1.4.13
      python: "3.3"
    - env: DJANGO=Django==1.4.13
      python: "3.4"
