sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
env:
  - DJANGO="Django~=2.0"
  - DJANGO="Django~=2.1"

matrix:
  exclude:
    - env: DJANGO="Django~=2.1"
      python: "3.4"

install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
script:
  - python runtests.py
