sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
env:
  - DJANGO="Django~=1.8.0"
  - DJANGO="Django~=1.9.0"
  - DJANGO="Django~=1.10.0"
  - DJANGO="Django~=1.11.0"

matrix:
  exclude:
    - env: DJANGO="Django~=1.9.0"
      python: "3.3"
    - env: DJANGO="Django~=1.10.0"
      python: "3.3"
    - env: DJANGO="Django~=1.11.0"
      python: "3.3"

install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
script:
  - python runtests.py
