language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DJANGO="Django<1.5"
  - DJANGO="Django<1.6"
  - DJANGO="Django<1.7"
  - DJANGO="Django<1.8"
  - DJANGO="Django<1.9"
install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
script:
  - python runtests.py

matrix:
  exclude:
    - env: DJANGO="Django<1.5"
      python: "3.3"
    - env: DJANGO="Django<1.5"
      python: "3.4"
